- name: create security group
  hosts: localhost
  vars_files:
    - group_vars/production.yml
  tasks:
  - name: create web
    ec2_group:
      name: web
      description: web security group
      region: "{{ region }}"
      vpc_id: "{{ vpc_id }}"
      rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0

